### ISSUE TITLE
Could not build "Fearless Wallet" project on m1 

### ISSUE THREAD

**Issue by leohar** [hyperledger/iroha-ios#126]
`Ld /Users/lpatolya/Library/Developer/Xcode/DerivedData/fearless-gdanpnshkzyxpyhifolhbauvynqn/Build/Products/Debug-iphonesimulator/IrohaCrypto/IrohaCrypto.framework/IrohaCrypto normal (in target 'IrohaCrypto' from project 'Pods')
    cd /Users/lpatolya/XcodeProjects/fearless-iOS/Pods
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -target x86_64-apple-ios11.0-simulator -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator14.5.sdk -L/Users/lpatolya/Library/Developer/Xcode/DerivedData/fearless-gdanpnshkzyxpyhifolhbauvynqn/Build/Products/Debug-iphonesimulator/IrohaCrypto -L/Users/lpatolya/XcodeProjects/fearless-iOS/Pods/IrohaCrypto/blake2Imp -L/Users/lpatolya/XcodeProjects/fearless-iOS/Pods/IrohaCrypto/ed25519Imp -L/Users/lpatolya/XcodeProjects/fearless-iOS/Pods/IrohaCrypto/sr25519Imp -F/Users/lpatolya/Library/Developer/Xcode/DerivedData/fearless-gdanpnshkzyxpyhifolhbauvynqn/Build/Products/Debug-iphonesimulator/IrohaCrypto -F/Users/lpatolya/Library/Developer/Xcode/DerivedData/fearless-gdanpnshkzyxpyhifolhbauvynqn/Build/Products/Debug-iphonesimulator/scrypt.c -F/Users/lpatolya/Library/Developer/Xcode/DerivedData/fearless-gdanpnshkzyxpyhifolhbauvynqn/Build/Products/Debug-iphonesimulator/secp256k1.c -filelist /Users/lpatolya/Library/Developer/Xcode/DerivedData/fearless-gdanpnshkzyxpyhifolhbauvynqn/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/IrohaCrypto.build/Objects-normal/x86_64/IrohaCrypto.LinkFileList -install_name @rpath/IrohaCrypto.framework/IrohaCrypto -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -dead_strip -Xlinker -object_path_lto -Xlinker /Users/lpatolya/Library/Developer/Xcode/DerivedData/fearless-gdanpnshkzyxpyhifolhbauvynqn/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/IrohaCrypto.build/Objects-normal/x86_64/IrohaCrypto_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -fprofile-instr-generate -lblake2 -led25519_sha2 -lsr25519crust -framework Foundation -framework scrypt -framework secp256k1 -Xlinker -no_adhoc_codesign -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/lpatolya/Library/Developer/Xcode/DerivedData/fearless-gdanpnshkzyxpyhifolhbauvynqn/Build/Intermediates.noindex/Pods.build/Debug-iphonesimulator/IrohaCrypto.build/Objects-normal/x86_64/IrohaCrypto_dependency_info.dat -o /Users/lpatolya/Library/Developer/Xcode/DerivedData/fearless-gdanpnshkzyxpyhifolhbauvynqn/Build/Products/Debug-iphonesimulator/IrohaCrypto/IrohaCrypto.framework/IrohaCrypto

ld: warning: ignoring file /Users/lpatolya/Library/Developer/Xcode/DerivedData/fearless-gdanpnshkzyxpyhifolhbauvynqn/Build/Products/Debug-iphonesimulator/scrypt.c/scrypt.framework/scrypt, building for iOS Simulator-x86_64 but attempting to link with file built for iOS Simulator-arm64
ld: warning: ignoring file /Users/lpatolya/Library/Developer/Xcode/DerivedData/fearless-gdanpnshkzyxpyhifolhbauvynqn/Build/Products/Debug-iphonesimulator/secp256k1.c/secp256k1.framework/secp256k1, building for iOS Simulator-x86_64 but attempting to link with file built for iOS Simulator-arm64
Undefined symbols for architecture x86_64:
  "_secp256k1_ecdsa_sign_recoverable", referenced from:
      -[SECSigner sign:error:] in SECSigner.o
  "_secp256k1_ecdsa_recover", referenced from:
      -[SECSignatureVerifier recoverFromSignature:forOriginalData:error:] in SECSignatureVerifier.o
  "_secp256k1_ec_pubkey_create", referenced from:
      -[SECKeyFactory deriveFromPrivateKey:error:] in SECKeyFactory.o
  "_secp256k1_ec_pubkey_serialize", referenced from:
      -[SECKeyFactory deriveFromPrivateKey:error:] in SECKeyFactory.o
      -[SECSignatureVerifier recoverFromSignature:forOriginalData:error:] in SECSignatureVerifier.o
  "_secp256k1_context_destroy", referenced from:
      -[SECKeyFactory deriveFromPrivateKey:error:] in SECKeyFactory.o
      -[SECSignatureVerifier recoverFromSignature:forOriginalData:error:] in SECSignatureVerifier.o
      -[SECSigner sign:error:] in SECSigner.o
  "_secp256k1_context_create", referenced from:
      -[SECKeyFactory deriveFromPrivateKey:error:] in SECKeyFactory.o
      -[SECSignatureVerifier recoverFromSignature:forOriginalData:error:] in SECSignatureVerifier.o
      -[SECSigner sign:error:] in SECSigner.o
  "_secp256k1_ecdsa_recoverable_signature_serialize_compact", referenced from:
      -[SECSigner sign:error:] in SECSigner.o
  "_secp256k1_ecdsa_recoverable_signature_parse_compact", referenced from:
      -[SECSignatureVerifier recoverFromSignature:forOriginalData:error:] in SECSignatureVerifier.o
  "_crypto_scrypt", referenced from:
      -[IRScryptKeyDeriviation deriveKeyFrom:salt:scryptN:scryptP:scryptR:length:error:] in IRScryptKeyDeriviation.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

<img width="1440" alt="Screenshot 2021-06-08 at 15 55 15" src="https://user-images.githubusercontent.com/16337578/121188624-f871cf80-c871-11eb-89dd-8b61e8c1bc52.png">

**Comment by ERussel** [comment]
It is not relevant for Iroha. Please, reopen the issue in https://github.com/soramitsu/fearless-utils-iOS
